### ISSUE TITLE
how to fix this

### ISSUE THREAD

**Issue by ghost** [gringoireDM/FBLikeLayout#10]
<img width="994" alt="screen shot 2015-10-16 at 11 16 01" src="https://cloud.githubusercontent.com/assets/8028679/10536926/5f7c5252-73f7-11e5-8522-090c0e60d0ee.png">

**Comment by liaogang** [comment]
You must implement `UICollectionViewDelegateFlowLayout` 
and add this method:

```
-(CGSize) collectionView:(UICollectionView *)collectionView layout:(UICollectionViewLayout     *)collectionViewLayout sizeForItemAtIndexPath:(NSIndexPath *)indexPath{
```
