### ISSUE TITLE
Custom Cell with outlets + constraints

### ISSUE THREAD

**Issue by achoura** [gringoireDM/FBLikeLayout#5]
Thank you for helping me
![ios simulator screen shot 21 feb 2015 3 07 40 pm](https://cloud.githubusercontent.com/assets/310606/6314371/65aa30ca-b9dc-11e4-897f-58c2b4234522.png)

**Comment by gringoireDM** [comment]
maybe you could explain a little your issue. What you have done? How did you use autolayout? It is clearly an autolayout problem. The layout does not touch in any way the content of each item

**Comment by gringoireDM** [comment]
This layout does not affect the content of cells. You problem must be found in you custom item implementation
