### ISSUE TITLE
Set cell at indexpath size manually

### ISSUE THREAD

**Issue by chlebta** [gringoireDM/FBLikeLayout#7]
Hello, I'm using this library and I want to know how to set cell at indexpath to max cellSize, I've tried this but it didn't work : 
-(CGSize) collectionView:(UICollectionView *)collectionView layout:(UICollectionViewLayout *)collectionViewLayout sizeForItemAtIndexPath:(NSIndexPath *)indexPath{
    if (indexPath.row == 0) {
        CGSize finalSize = SetMaxCellSize;
        return finalSize;
    } else {
    CGSize finalSize = setNormalSize;
    return finalSize;
    }
}

**Comment by gringoireDM** [comment]
Read the documentation. 
layout.maxCellSpace
This parameter let you set how many "squares" maximum a full image can be. In the sample code we have a maximum of 3 "squares". The size for item should always return the full image size. 

Again, read the documentation and the sample code.

**Comment by chlebta** [comment]
@gringoireDM 
Yeah I've readed that but the problem in the sizeForItemAtIndexPath method I can't do this 

```
CGSize finalSize = layout.maxCellSpace;
return finalSize;
```

because layout.maxCellSpace : 
- First : is **NSInteger** type not **CGSize** 
- Second : it's property of **FBLikeLayout** not **UICollectionViewLayout** and in the **-(CGSize) collectionView:(UICollectionView *)collectionView layout:(UICollectionViewLayout *)collectionViewLayout sizeForItemAtIndexPath:(NSIndexPath *)indexPath;** method the layout property is **UIViewCollectionLayout** type.

**Comment by gringoireDM** [comment]
No you have not read it. maxCellSpace is the maximum number of squares that a full image should fit. of course it is an NSInteger. finalSize should ALWAYS be the image size, then the library will choose randomly if to show the image as a square, or as full image size.

Please, download the sample code and understand it.

**Comment by chlebta** [comment]
I little bit confused about how it work's so can you just tell me how to set my first Image to fullImage size and the rest of image to normal size ?

**Comment by gringoireDM** [comment]
It would be an hack.
This layout was not designed to work this way, and you would incur in useless performance issues. Just make a custom layout by yourself. if the only requirement is that it should have the first image as full image then it should take less than few hours to be done.

By the way, if you don't care about performance issues, just set the layout.fullImagePercentageOfOccurrency to 100 then as size of your layout delegate method pass the image size if the item is 0, or (CGSize){layout.singleCellWidth, layout.singleCellWidth} if it is not the first element.

I repeat: This layout is not designed to work this way. it is an hack, and you could incur in useless performance issues.

**Comment by chlebta** [comment]
Oke thank's , then I think It's better to design my own layout can you give some auto link that can be helpful this first time I work with UIcollectionView and I'm new IOS developer

**Comment by gringoireDM** [comment]
The official documentation page is the best link i think you should study. It is clear and explains mostly everything you can do with layout subclassing. a small google resarch about UICollectionViewFlowLayout will help you for sure.
