### ISSUE TITLE
cocoapods install too slow

### ISSUE THREAD

**Issue by jevonszmx** [gringoireDM/FBLikeLayout#9]
May be there are too many pics, so every time when i use "pod install", it's very very slow !!!

I have use --verbose to see more details,  pod give me these message:

``` shell
$/usr/bin/git clone https://github.com/gringoireDM/FBLikeLayout.git
     /Volumes/Data/Documents/App/app/imeili/Pods/FBLikeLayout --single-branch
     --depth 1 --branch 1.2
```

Total more than 13MB , but core code just 21 kb .....

I do like this repo~~

Help...

Ths ~

**Comment by gringoireDM** [comment]
Pictures are not included in the podspec file. This is not an issue.
